esphome:
  name: esp8266
  friendly_name: ESP8266
  min_version: 2025.3.2

esp8266:
  board: esp01_1m
  restore_from_flash: true

logger:
  baud_rate: 115200
  level: INFO
  logs:
    component: ERROR
    http_request.arduino: ERROR

api:
  encryption:
    key: !secret proxy_api_encryption_key
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 24h

packages:
  solar_router:
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    refresh: 1d
    files:
      - path: solar_router/common.yaml
      - path: solar_router/power_meter_home_assistant.yaml
        vars:
          main_power_sensor: "sensor.smart_meter_ts_100a_1_puissance_reelle"
          consumption_sensor: "sensor.solarnet_power_load_consumed"
      - path: solar_router/regulator_mecanical_relay.yaml
        vars:
          relay_regulator_gate_pin: GPIO0
      - path: solar_router/engine_1switch.yaml
        vars:
          green_led_pin: GPIO1
          green_led_inverted: 'True'
          yellow_led_pin: GPIO2
      - path: solar_router/temperature_limiter_home_assistant.yaml
        vars:
          temperature_sensor: "input_number.test_temperature"
          red_led_pin: GPIO4

